// Package usage is a minimal metering layer for per-(apikey, agent, day)
// resource counters. Used by admin endpoints to answer "how much did this
// tenant consume?" — the data that eventually drives billing / quota.
//
// Intentionally not a full billing system: no sub-second granularity, no
// write-ahead log, no dedup. Counters are incremented at the hot points
// that matter (LLM turn, sandbox lifetime, workspace bytes) and flushed
// async so hot paths don't block on DB. Good enough for dashboards and
// fair-use quota; real billing should export these daily to a separate
// system.
package usage

import (
	"context"
	"sync"
	"time"
)

// Kind enumerates what's being counted. Adding a new kind means: add the
// const, add the column to the SQL table, and call Meter.Add from the
// hot-path code that produces it.
type Kind string

const (
	// TokensIn is the number of prompt tokens the LLM consumed. Incremented
	// at the end of each provider call. Drives most of the cost.
	TokensIn Kind = "tokens_in"
	// TokensOut is completion tokens generated by the LLM.
	TokensOut Kind = "tokens_out"
	// SandboxSeconds is how many seconds of sandbox runtime the agent used
	// (measured between sandbox creation and idle-eviction).
	SandboxSeconds Kind = "sandbox_seconds"
	// WorkspaceBytes is the cumulative bytes written to workspace store.
	// Charged once at write time — not billed for storage at rest (that's
	// on the operator's S3 bill).
	WorkspaceBytes Kind = "workspace_bytes"
)

// Event is one unit of metering. APIKey may be empty for admin-owned
// agents; the Meter still records the event under the agent id and the
// "" key, which the admin UI renders as "admin".
type Event struct {
	When    time.Time
	Day     time.Time // UTC date, truncated to midnight — primary key dimension
	APIKey  string
	Agent   string
	Kind    Kind
	Count   int64 // tokens, seconds, bytes — units depend on Kind
}

// Meter is the recording interface. Two implementations currently:
// MemMeter (in-process, lost on restart, fine for dev / single-node) and
// the SQL-backed version (durable, aggregated by day).
type Meter interface {
	Add(ctx context.Context, apiKey, agent string, kind Kind, count int64)
	Query(ctx context.Context, q Query) ([]DailyRow, error)
	Close() error
}

// Query filters Meter readbacks. Empty slice of kinds means "all".
type Query struct {
	APIKey string    // "" = all keys (admin view)
	Agent  string    // "" = all agents for that key
	Kinds  []Kind    // empty = all kinds
	Since  time.Time // UTC; default last 30 days if zero
	Until  time.Time // UTC; default now if zero
}

// DailyRow is one aggregated cell of the result: one (day, apikey, agent,
// kind) combination and its total.
type DailyRow struct {
	Day    time.Time
	APIKey string
	Agent  string
	Kind   Kind
	Count  int64
}

// -------- MemMeter --------

// MemMeter keeps counters in a map — works everywhere, loses state on
// restart. Good for local / single-pod deployments and for tests.
type MemMeter struct {
	mu   sync.Mutex
	data map[memKey]int64
}

type memKey struct {
	day    time.Time
	apiKey string
	agent  string
	kind   Kind
}

func NewMemMeter() *MemMeter {
	return &MemMeter{data: make(map[memKey]int64)}
}

func dayBucket(t time.Time) time.Time {
	t = t.UTC()
	return time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
}

func (m *MemMeter) Add(ctx context.Context, apiKey, agent string, kind Kind, count int64) {
	if count == 0 {
		return
	}
	k := memKey{day: dayBucket(time.Now()), apiKey: apiKey, agent: agent, kind: kind}
	m.mu.Lock()
	m.data[k] += count
	m.mu.Unlock()
}

func (m *MemMeter) Query(ctx context.Context, q Query) ([]DailyRow, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	// Default time range: last 30 days → now.
	if q.Since.IsZero() {
		q.Since = time.Now().AddDate(0, 0, -30).UTC()
	}
	if q.Until.IsZero() {
		q.Until = time.Now().UTC()
	}
	kindSet := map[Kind]bool{}
	for _, k := range q.Kinds {
		kindSet[k] = true
	}
	var out []DailyRow
	for k, count := range m.data {
		if q.APIKey != "" && k.apiKey != q.APIKey {
			continue
		}
		if q.Agent != "" && k.agent != q.Agent {
			continue
		}
		if len(kindSet) > 0 && !kindSet[k.kind] {
			continue
		}
		if k.day.Before(dayBucket(q.Since)) || k.day.After(q.Until) {
			continue
		}
		out = append(out, DailyRow{
			Day:    k.day,
			APIKey: k.apiKey,
			Agent:  k.agent,
			Kind:   k.kind,
			Count:  count,
		})
	}
	return out, nil
}

func (m *MemMeter) Close() error { return nil }
