// Auto-generated by scripts/db-studio.sh. Re-runs of the script overwrite
// this file; safe to delete when not needed. drizzle-kit studio reads it
// to know which dialect/credentials to introspect.
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "sqlite",
  dbCredentials: { url: "/Users/mike/.fastclaw/fastclaw.db" },
});
